// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQM3kjUOA5G0g44f_zVN2wLf7zc9ojBZg',
    appId: '1:708070786763:web:4b65ce283ceef73f94bd4e',
    messagingSenderId: '708070786763',
    projectId: 'gdsc-406014',
    authDomain: 'gdsc-406014.firebaseapp.com',
    databaseURL: 'https://gdsc-406014-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gdsc-406014.appspot.com',
    measurementId: 'G-VDT4MDH9Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8_jEcsh2jtrnblfnGvw2eG8YuFjVgSp0',
    appId: '1:708070786763:android:4cc05f0e46fd66b994bd4e',
    messagingSenderId: '708070786763',
    projectId: 'gdsc-406014',
    databaseURL: 'https://gdsc-406014-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gdsc-406014.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbbD07Ffl3xQI0sQWQghDoNj2KiwISVug',
    appId: '1:708070786763:ios:bdff55644d79933094bd4e',
    messagingSenderId: '708070786763',
    projectId: 'gdsc-406014',
    databaseURL: 'https://gdsc-406014-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gdsc-406014.appspot.com',
    iosBundleId: 'com.example.gdsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbbD07Ffl3xQI0sQWQghDoNj2KiwISVug',
    appId: '1:708070786763:ios:a84ca64a4be3615994bd4e',
    messagingSenderId: '708070786763',
    projectId: 'gdsc-406014',
    databaseURL: 'https://gdsc-406014-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gdsc-406014.appspot.com',
    iosBundleId: 'com.example.gdsc.RunnerTests',
  );
}
