// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBWk800un3-lCU-77R-15MgXEU8PykKic',
    appId: '1:462186489423:web:01c297525fb6aa847aec3a',
    messagingSenderId: '462186489423',
    projectId: 'potent-result-406711',
    authDomain: 'potent-result-406711.firebaseapp.com',
    storageBucket: 'potent-result-406711.appspot.com',
    measurementId: 'G-GP589CPD7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQPK06XXobbJbvzNA07AJKxBbPfu0pST0',
    appId: '1:462186489423:android:1592934c90b57c527aec3a',
    messagingSenderId: '462186489423',
    projectId: 'potent-result-406711',
    storageBucket: 'potent-result-406711.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANhrh7_1BgTMYur-9AzLugKB5eE26KnGY',
    appId: '1:462186489423:ios:fa94c493c6d244c17aec3a',
    messagingSenderId: '462186489423',
    projectId: 'potent-result-406711',
    storageBucket: 'potent-result-406711.appspot.com',
    iosBundleId: 'com.example.gdsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANhrh7_1BgTMYur-9AzLugKB5eE26KnGY',
    appId: '1:462186489423:ios:e14b8ffc111c07817aec3a',
    messagingSenderId: '462186489423',
    projectId: 'potent-result-406711',
    storageBucket: 'potent-result-406711.appspot.com',
    iosBundleId: 'com.example.gdsc.RunnerTests',
  );
}
